# Emacs mode:  -*-Makefile-*-
#
# Windows nmake makefile.  We expect to call this from
# "../naviserver/Makefile.win32", NOT directly.

!ifndef NS_DIR
!ifdef NAVISERVER
NS_DIR = $(NAVISERVER)
!else
NS_DIR = ..\naviserver
!endif
!endif

MOD      = nszlib.dll
DLL      = nszlib
MODOBJS  = nszlib.o

DEFS = $(DEFS) /I $(zlib_include)
LIBS = $(LIBS) $(zlib_lib)\zlib.lib

!include "$(NS_DIR)\include\Makefile.win32"
